[package]
name = "nannou-project"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "desintegrate",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
